openapi: 3.0.1
info:
  title: Kologermit's URL shortener
  description: |-
    Description
  contact:
    email: kologermit@gmail.com
servers:
  - url: http://kologermit.ru:8000/
tags:
  - name: Ссылка
  - name: Перенаправление
paths:
  /link/create/:
    post:
      tags:
      - Ссылка
      description: Создание 
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "link"
        description: ""
        required: true
        type: string
        example: http://vk.com/kologermit
      responses:
        "200":
          description: Успех создания
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Link'
        400:
          description: "Client Error"
        500:
          description: "Server Error"  
  /link/delete/:
    delete:
      tags:
      - Ссылка
      description: Удаление 
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "id"
        description: ""
        required: true
        type: integer
        example: 1
      responses:
        "200":
          description: Успех удаления
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Link'
        400:
          description: "Client Error"
        500:
          description: "Server Error"
  /link/get_info/:
    get:
      tags:
      - Ссылка
      description: Создание 
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "id"
        description: ""
        required: true
        type: integer
        example: 1
      responses:
        "200":
          description: Успех
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Link'
        400:
          description: "Client Error"
        500:
          description: "Server Error"
  /{link_code}/:
    get:
      tags:
      - Перенаправление
      description: Перенаправление 
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "link_code"
        description: "Код перенаправленной ссылки"
        required: true
        type: string
        example: AMCYRT
      responses:
        302:
          description: Перенаправление
        404:
          description: Код не найден
      
components:
  schemas:
    Link:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        code:
          type: string
          example: AMCYRT
        url:
          type: string
          example: http://vk.com/kologermit
        redirect_url:
          type: string
          example: http://kologermit.ru:8001/AMCYRT
        create_date:
          type: "string"
          format: "date-time"
      