version: '3.1'

services:
  api:
    build: ./api
    ports:
      - ${API_PORT:-8000}:8080
    environment:
      - DOC_HOST=${DOC_HOST:-http://localhost:8001}
      - HOST=${API_HOST:-http://localhost:8000}
    volumes:
      - ./api:/app
    
  doc:
    image: swaggerapi/swagger-ui
    ports:
      - ${API_DOC_PORT:-8001}:8080
    volumes:
      - ./api.yml:/usr/share/nginx/html/swagger/api.yaml
    environment:
      API_URL: swagger/api.yaml
    depends_on:
      - api
