version: '3.1'

services:
  api:
    build: ./api
    ports:
      - ${API_PORT:-8080}:8080
    volumes:
      - ./api:/app
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - ${API_DOC_PORT:-8001}:8080
    volumes:
      - ./api.yml:/usr/share/nginx/html/swagger/api.yaml
    environment:
      API_URL: swagger/api.yaml
